name: 'Scheduled Workflow'
run-name: 'Testing Scheduled Workflow'
on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
